services:
  app:
    container_name: agenda-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongo://admin:passwrod@:mongo:27017/my_database
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=my_database
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

    volumes:
      - ./app/data:/data/db
      - ./create_ddbb.js:/docker-entrypoint-initdb.d/create_ddbb.js:ro

    ports:
      - 27017:27017